apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-storageclass
allowVolumeExpansion: true 
provisioner: disk.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  skuname: StandardSSD_LRS