apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fullcycle
  region: us-east-2
  version: "1.30"

iam:
  withOIDC: true

managedNodeGroups:
  - name: ng-app
    instanceType: t3.medium
    desiredCapacity: 3
    labels:
      type: ec2
    iam:
      withAddonPolicies:
        ebs: true

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
  - name: codeflix
    selectors:
      - namespace: codeflix
        labels:
          schedule_on: fargate

addons:
  - name: aws-ebs-csi-driver
    version: latest