apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-storageclass
  claimRef:
    namespace: codeflix
    name: mysql-volume-mysql-0
  awsElasticBlockStore:
    volumeID: vol-0e977d0b96924b862
    fsType: ext4
