apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: codeflix
spec:
  instances: 1
  db:
    vendor: mysql
    host: mysql-0.mysql-h.codeflix.svc.cluster.local
    usernameSecret:
      name: db-secret
      key: username
    passwordSecret:
      name: db-secret
      key: password
  http:
    httpEnabled: true
  hostname:
    hostname: http://keycloak-service:8080
    strict: false
  resources:
    requests:
      cpu: 800m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  unsupported:
    podTemplate:
      metadata:
        labels:
          schedule_on: fargate