apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-storageclass
allowVolumeExpansion: true 
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp3