apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fullcycle
  region: us-east-2
  version: "1.30"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

managedNodeGroups:
  - name: ng-app
    instanceType: t3.medium
    desiredCapacity: 4
    labels:
      type: ec2
    iam:
      withAddonPolicies:
        ebs: true
        awsLoadBalancerController: true

addons:
  - name: aws-ebs-csi-driver
    version: latest