apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-storageclass
allowVolumeExpansion: true 
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: pd-balanced # Alternativas: pd-standard, pd-ssd
  replication-type: none # Alternativas: regional-pd para replicação regional